import {_decorator,Component,Node,Canvas,Camera,Layers,UITransform,Label,Color,Vec3,director,input,Input,EventKeyboard,KeyCode,Graphics,game,Game,view,HorizontalTextAlignment,VerticalTextAlignment} from 'cc';
import {GameFlow} from './GameFlow';import {InputController,MoveDir} from './InputController';import {InteractionResolver} from './InteractionResolver';import {ShadowLayout,switchX} from './ShadowLayout';
const {ccclass}=_decorator;
@ccclass('ShadowCatBootstrap') export class ShadowCatBootstrap extends Component{
 private flow=new GameFlow();private inputCtl:InputController|null=null;private resolver:InteractionResolver|null=null;private root:Node|null=null;private contentRoot:Node|null=null;private status:Label|null=null;private hint:Label|null=null;private realCat:Node|null=null;private shadowCat:Node|null=null;private levelsPage=0;private navTapAt=0;private pausedByBackground=false;
 start(){this.ensureUiRoot();this.showHome();input.on(Input.EventType.KEY_DOWN,this.onKeyDown,this);game.on(Game.EVENT_HIDE,this.onAppHide,this);game.on(Game.EVENT_SHOW,this.onAppShow,this);}onDestroy(){input.off(Input.EventType.KEY_DOWN,this.onKeyDown,this);game.off(Game.EVENT_HIDE,this.onAppHide,this);game.off(Game.EVENT_SHOW,this.onAppShow,this);}
 update(dt:number){const before=this.flow.page;this.flow.update(dt);if(before==='playing'&&this.flow.page==='result'){this.showResult();return;}if(this.flow.page==='playing'&&this.flow.core){this.syncActors();this.refreshStatus();}}
 private onAppHide(){this.flow.onHide();if(this.flow.page==='playing'){this.pausedByBackground=true;this.pause('游戏已暂停','已从后台返回，点击继续后恢复本关');}}
 private onAppShow(){this.flow.onShow();if(this.pausedByBackground&&this.flow.page==='paused'){this.showPause('游戏已暂停','已从后台返回，点击继续后恢复本关');}this.pausedByBackground=false;}
 private ensureUiRoot(){if(this.root)return;const scene=director.getScene();if(!scene)return;const cn=new Node('ShadowCatCanvas');cn.layer=Layers.Enum.UI_2D;const canvas=cn.addComponent(Canvas);cn.addComponent(UITransform).setContentSize(720,1280);const camN=new Node('UICamera');camN.layer=Layers.Enum.UI_2D;const cam=camN.addComponent(Camera);cam.projection=Camera.ProjectionType.ORTHO;cam.visibility=Layers.Enum.UI_2D;camN.setPosition(0,0,1000);cn.addChild(camN);canvas.cameraComponent=cam;const content=new Node('SafeContent');content.layer=Layers.Enum.UI_2D;content.addComponent(UITransform).setContentSize(720,1280);cn.addChild(content);const visible=view.getVisibleSize();const scale=Math.min(1,visible.width/720,visible.height/1280);content.setScale(scale,scale,1);scene.addChild(cn);this.root=cn;this.contentRoot=content;}
 private clear(){if(!this.contentRoot)return;[...this.contentRoot.children].forEach(n=>n.destroy());this.status=null;this.hint=null;this.realCat=null;this.shadowCat=null;}
 private clearRunRefs(){this.inputCtl=null;this.resolver=null;}
 private setupLabel(l:Label,t:string,s:number,c:Color){l.string=t;l.fontSize=s;l.lineHeight=s+8;l.color=c;l.horizontalAlign=HorizontalTextAlignment.CENTER;l.verticalAlign=VerticalTextAlignment.CENTER;}
 private makeText(t:string,y:number,s=36,c=new Color(35,35,45,255)){const n=new Node('Text');n.layer=Layers.Enum.UI_2D;n.addComponent(UITransform).setContentSize(660,90);const l=n.addComponent(Label);this.setupLabel(l,t,s,c);n.setPosition(0,y,0);this.contentRoot?.addChild(n);return l;}
 private makePanel(name:string,x:number,y:number,w:number,h:number,c:Color){const n=new Node(name);n.layer=Layers.Enum.UI_2D;n.addComponent(UITransform).setContentSize(w,h);const g=n.addComponent(Graphics);g.fillColor=c;g.roundRect(-w/2,-h/2,w,h,18);g.fill();n.setPosition(x,y,0);this.contentRoot?.addChild(n);return n;}
 private makeButton(t:string,x:number,y:number,fn:()=>void,w=210,h=76,guard=true){const n=this.makePanel(`Btn_${t}`,x,y,w,h,new Color(235,240,252,255));const ln=new Node('Label');ln.layer=Layers.Enum.UI_2D;ln.addComponent(UITransform).setContentSize(w,h);const l=ln.addComponent(Label);this.setupLabel(l,t,26,new Color(35,35,45,255));n.addChild(ln);n.on(Node.EventType.TOUCH_END,()=>{if(guard){const now=Date.now();if(now-this.navTapAt<120)return;this.navTapAt=now;}fn();},this);return n;}
 private makeCat(name:string,y:number,c:Color){const n=new Node(name);n.layer=Layers.Enum.UI_2D;n.addComponent(UITransform).setContentSize(76,76);const g=n.addComponent(Graphics);g.fillColor=c;g.circle(0,0,32);g.fill();n.setPosition(-220,y,0);this.contentRoot?.addChild(n);return n;}
 private drawLightBadge(name:string,x:number,y:number,requiredLight:number,done:boolean){if(done)return;const c=requiredLight?new Color(255,224,95,235):new Color(95,125,180,235);this.makePanel(name,x+22,y+22,18,18,c);}
 private drawObjectives(){const c=this.flow.core;if(!c)return;for(let i=0;i<c.level.realSwitches;i++){const x=switchX(i,c.level.realSwitches),done=c.isRealDone(i);this.makePanel(`RealSwitch_${i}`,x,ShadowLayout.REAL_Y,30,30,done?new Color(110,205,125,255):new Color(235,145,85,255));if(i<c.level.lightGates)this.drawLightBadge(`RealLight_${i}`,x,ShadowLayout.REAL_Y,i%2,done);}for(let i=0;i<c.level.shadowSwitches;i++){const x=switchX(i,c.level.shadowSwitches),done=c.isShadowDone(i);this.makePanel(`ShadowSwitch_${i}`,x,ShadowLayout.SHADOW_Y,30,30,done?new Color(110,205,125,255):new Color(135,120,210,255));if(i<c.level.lightGates)this.drawLightBadge(`ShadowLight_${i}`,x,ShadowLayout.SHADOW_Y,i%2,done);}}
 private showHome(){this.flow.goHome();this.clearRunRefs();this.clear();this.makeText('影子小猫',420,56);this.makeText('一只猫，两种世界规则',340,28);this.makeButton('开始游戏',0,160,()=>this.startLevel(this.flow.save.unlockedLevel));this.makeButton('关卡选择',0,60,()=>this.showLevels(0));this.makeButton('玩法说明',0,-40,()=>this.showTutorial());}
 private showLevels(page=this.levelsPage){this.flow.openLevels();this.clearRunRefs();this.levelsPage=Math.max(0,Math.min(2,page));this.clear();this.makeText('选择关卡',470,46);this.makeText(['镜像基础','镜像进阶 · 追影觉醒','光影变位'][this.levelsPage],415,24,new Color(75,75,110,255));const start=this.levelsPage*10+1,end=Math.min(30,start+9);for(let i=start;i<=end;i++){const col=(i-start)%2,row=Math.floor((i-start)/2),ok=i<=this.flow.save.unlockedLevel;this.makeButton(ok?`第${i}关`:`第${i}关 未解锁`,-130+col*260,300-row*100,()=>{if(ok)this.startLevel(i);},230,72);}if(this.levelsPage>0)this.makeButton('上一页',-130,-300,()=>this.showLevels(this.levelsPage-1));if(this.levelsPage<2)this.makeButton('下一页',130,-300,()=>this.showLevels(this.levelsPage+1));this.makeButton('返回首页',0,-400,()=>this.showHome());}
 private showTutorial(){this.flow.openTutorial();this.clearRunRefs();this.clear();this.makeText('三种影子规则',440,46);this.makeText('镜像：影子与现实反向移动',300,25);this.makeText('追影：影子落后数步，可主动让它追上',225,25);this.makeText('光影：切换明暗会改变影子的横向位置',150,25);this.makeText('机关角标：金色需亮光，蓝色需暗光',75,22);this.makeText('靠近彩色机关后互动，绿色表示已完成',15,22);this.makeButton('返回首页',0,-300,()=>this.showHome());}
 private startLevel(level:number){this.flow.startLevel(level);if(!this.flow.core)return;this.inputCtl=new InputController(this.flow.core);this.resolver=new InteractionResolver(this.flow.core);this.renderPlaying();}
 private renderPlaying(){const c=this.flow.core;if(!c)return;this.clear();this.makeText(`第 ${this.flow.level} 关`,520,36);this.makeText(this.modeText(),470,22,new Color(80,70,130,255));this.status=this.makeText('',430,20);this.hint=this.makeText(this.modeHint(),390,19);this.makePanel('RealWorld',0,ShadowLayout.REAL_Y-5,650,170,new Color(255,245,222,255));this.makePanel('ShadowWorld',0,ShadowLayout.SHADOW_Y+5,650,170,new Color(225,220,247,255));this.makePanel('RealExit',ShadowLayout.EXIT_X,ShadowLayout.REAL_Y,42,118,new Color(170,225,170,255));this.makePanel('ShadowExit',ShadowLayout.EXIT_X,ShadowLayout.SHADOW_Y,42,118,new Color(155,190,215,255));this.drawObjectives();this.realCat=this.makeCat('RealCat',ShadowLayout.REAL_Y,new Color(255,170,75,255));this.shadowCat=this.makeCat('ShadowCat',ShadowLayout.SHADOW_Y,new Color(105,90,170,255));this.makeButton('↑',0,-300,()=>this.move('up'),130,64,false);this.makeButton('←',-155,-375,()=>this.move('left'),130,64,false);this.makeButton('↓',0,-375,()=>this.move('down'),130,64,false);this.makeButton('→',155,-375,()=>this.move('right'),130,64,false);if(c.level.shadowMode==='lag'){this.makeButton('互动',-240,-470,()=>this.interact(),130,64,false);this.makeButton('影子追步',-80,-470,()=>this.catchUpShadow(),145,64,false);this.makeButton('切换光照',85,-470,()=>this.toggleLight(),145,64,false);this.makeButton('暂停',240,-470,()=>this.pause(),120,64);}else{this.makeButton('互动',-220,-470,()=>this.interact(),145,68,false);this.makeButton('切换光照',0,-470,()=>this.toggleLight(),175,68,false);this.makeButton('暂停',220,-470,()=>this.pause(),145,68);}this.syncActors();this.refreshStatus();}
 private modeText(){const m=this.flow.core?.level.shadowMode;if(m==='lag')return '追影模式 · 影子会延迟执行动作';if(m==='light-shift')return '光影模式 · 明暗决定影子横向位置';return '镜像模式 · 影子与现实反向移动';}
 private modeHint(){const c=this.flow.core;if(!c)return '';if(c.level.shadowMode==='lag')return `影子当前还有 ${c.pendingShadowSteps()} 步未跟上`;if(c.level.shadowMode==='light-shift')return '切换明暗匹配机关角标，并观察影子位置';if(c.level.lightGates>0)return '机关角标：金色需亮光，蓝色需暗光';return '靠近彩色机关互动，再前往右侧出口';}
 private move(d:MoveDir){if(this.flow.page!=='playing')return;this.inputCtl?.move(d);this.syncActors();this.refreshStatus();}private catchUpShadow(){if(this.flow.page!=='playing'||!this.flow.core)return;const moved=this.inputCtl?.catchUpShadow()||false;if(this.hint)this.hint.string=moved?`影子追上一步，还剩 ${this.flow.core.pendingShadowSteps()} 步`:'影子已经跟上现实';this.syncActors();this.refreshStatus();}private toggleLight(){if(this.flow.page!=='playing')return;this.inputCtl?.toggleLight();this.syncActors();this.refreshStatus();if(this.hint){const c=this.flow.core;this.hint.string=c?.level.shadowMode==='light-shift'?`光照已切换为${c.light?'亮':'暗'}，影子位置已改变`:`光照已切换为${c?.light?'亮':'暗'}，重新判断光照机关`;}}
 private interact(){if(this.flow.page!=='playing'||!this.resolver)return;const r=this.resolver.interact();if(this.hint)this.hint.string=r.message;if(r.completed&&this.flow.tryComplete(r.realAtExit,r.shadowAtExit)){this.showResult();return;}if(r.changed){this.renderPlaying();return;}this.refreshStatus();}
 private pause(title='已暂停',note='本关计时已停止'){if(this.flow.page==='playing')this.flow.pause();if(this.flow.page!=='paused')return;this.showPause(title,note);}
 private showPause(title:string,note:string){this.clear();this.makeText(title,290,54);this.makeText(note,215,22,new Color(75,75,100,255));this.makeButton('继续游戏',0,70,()=>this.resumeFromPause());this.makeButton('重新开始',0,-30,()=>this.startLevel(this.flow.level));this.makeButton('返回首页',0,-130,()=>this.showHome());}
 private resumeFromPause(){if(this.flow.page!=='paused')return;this.pausedByBackground=false;this.flow.resume();this.renderPlaying();}
 private showResult(){this.clearRunRefs();this.clear();if(this.flow.resultSuccess){this.makeText('通关成功',320,54);this.makeText(`星级：${'★'.repeat(this.flow.resultStars)}${'☆'.repeat(3-this.flow.resultStars)}`,230,34);this.makeText(this.modeText(),170,22);if(this.flow.level<30)this.makeButton('下一关',0,45,()=>{this.flow.nextLevel();if(this.flow.core){this.inputCtl=new InputController(this.flow.core);this.resolver=new InteractionResolver(this.flow.core);this.renderPlaying();}});}else{this.makeText('时间到',320,54);this.makeText('本次进度不会覆盖最佳成绩',230,26);}this.makeButton('重试',0,-50,()=>this.startLevel(this.flow.level));this.makeButton('关卡选择',0,-150,()=>this.showLevels(Math.floor((this.flow.level-1)/10)));this.makeButton('返回首页',0,-250,()=>this.showHome());}
 private syncActors(){const c=this.flow.core;if(!c)return;this.realCat?.setPosition(new Vec3(c.real.x,c.real.y,0));this.shadowCat?.setPosition(new Vec3(c.shadow.x,c.shadow.y,0));}private refreshStatus(){if(!this.status||!this.flow.core)return;const c=this.flow.core;const time=c.level.timeLimit>0?` · ${Math.max(0,Math.ceil(c.level.timeLimit-c.elapsed))}s`:'';const lag=c.level.shadowMode==='lag'?` · 待追 ${c.pendingShadowSteps()} 步`:'';this.status.string=`现实 ${c.realActivated}/${c.level.realSwitches} · 影子 ${c.shadowActivated}/${c.level.shadowSwitches} · ${c.light?'亮':'暗'}${lag}${time}`;}
 private onKeyDown(e:EventKeyboard){if(e.keyCode===KeyCode.ESCAPE){if(this.flow.page==='playing')this.pause();else if(this.flow.page==='paused')this.resumeFromPause();else if(this.flow.page==='levels'||this.flow.page==='tutorial'||this.flow.page==='result')this.showHome();return;}if(this.flow.page!=='playing')return;if(e.keyCode===KeyCode.SPACE){this.interact();return;}if(e.keyCode===KeyCode.KEY_F){this.catchUpShadow();return;}if(e.keyCode===KeyCode.KEY_L){this.toggleLight();return;}const map:Partial<Record<KeyCode,MoveDir>>={[KeyCode.ARROW_LEFT]:'left',[KeyCode.KEY_A]:'left',[KeyCode.ARROW_RIGHT]:'right',[KeyCode.KEY_D]:'right',[KeyCode.ARROW_UP]:'up',[KeyCode.KEY_W]:'up',[KeyCode.ARROW_DOWN]:'down',[KeyCode.KEY_S]:'down'};const d=map[e.keyCode];if(d)this.move(d);}
}
